name: "Build and Deploy"

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3   # reads from a '.ruby-version' or '.tools-version' file if 'ruby-version' is omitted
          bundler-cache: true
      - name: Build Assets
        run: npm i && npm run build
      
      - name: Build Site
        run: bundle exec jekyll b
        env:
          JEKYLL_ENV: "production"
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.SERVER }}
          port: 22
          local_path: ${{ secrets.LOCAL_PATH }}
          remote_path: ${{ secrets.REMOTE_PATH }}
          delete_remote_files: true
          password: ${{ secrets.PASSWORD }}
